version: '3'

services:
  app:
    container_name: ${APP_NAME}-app
    build:
      context: ./.docker
      dockerfile: Dockerfile
      args:
        - IMAGE_VERSION=2.0.1-npm
    image: ${APP_NAME}/php:latest
    working_dir: /var/www/html
    restart: unless-stopped
    tty: true
    env_file:
      - ./.env
    volumes:
      - .:/var/www/html
    ports:
      - '${FORWARD_APP_PORT:-80}:80'
    networks:
      - application-network
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: ${APP_NAME}-db
    image: mysql:8.0.27
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 5
      timeout: 5s
    volumes:
      - 'mysql-data:/var/lib/mysql'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    networks:
      - application-network

  redis:
    container_name: ${APP_NAME}-redis
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis-data:/data'
    networks:
      - application-network
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

  mailpit:
    container_name: ${APP_NAME}-mailpit
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - application-network

  selenium:
    container_name: ${APP_NAME}-selenium
    image: selenium/standalone-chrome:latest
    networks:
      - application-network

networks:
  application-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
